language: csharp
mono: none
dotnet: 2.2.104
dist: xenial

jobs:
  include:
    - name: "Lint for Python syntax errors and undefined names"
      language: python
      addons: true  # override
      install: pip install flake8
      script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: "Change detection"
      if: type = pull_request
      script: ./detect-pr-changes.sh
    - name: "Cloud APIs A-L"
      env: API_REGEX='Google\.Cloud\.[A-L].*'
    - name: "Cloud APIs M-Z"
      env: API_REGEX='Google\.Cloud\.[M-Z].*'
    - name: "Non-Cloud APIs"
      env: API_REGEX='!Google\.Cloud'

# Install the .NET Core 1.0 runtime as that's what we test against
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5

# Autosynth pushes directly to the main fork, rather than a separate fork.
# We want to build the PR, but not the branch directly, partly as change
# detection fails, but mostly because we don't really need to.
branches:
  only:
  - master

script:
  - python3 tools/listapis.py apis/apis.json > /dev/null || travis_terminate 1
  - touch build_timing_log.txt
  - ./build.sh --diff --regex $API_REGEX
  - ./processbuildtiminglog.sh
