# Version for the build. We make it clear that it's
# Appveyor as this isn't a version we expect to make
# it elsewhere...
version: 1.0.{build}-appveyor

image: Visual Studio 2019

branches:
  only:
    - master

init:
  - git config --global core.autocrlf true
  # This change was recommended by the AppVeyor team to save space.
  - rmdir C:\cygwin /s /q
  - rmdir C:\QT /s /q

# Install the pre-requisites for the build.
install:
  # add dotnet and curl to PATH
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;C:\Program Files\Git\mingw64\bin;$env:Path"

# Perform the build.
build_script:
  - bash appveyor.sh

test: off
deploy: off
