name: Build and test PR (changed APIs only)

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    strategy:
      matrix:
        regex: ["'Google\\.Cloud\\.[A-L].*'", "'Google\\.Cloud\\.[M-Z].*'", "'!Google\\.Cloud'"]
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 100

    # The GitHub checkout action leaves the repo in a slightly awkward
    # state. This tidies it up.
    - name: Set up git branches
      run: |
        git checkout -b pr-head
        git checkout -b master ${{ github.event.pull_request.base.sha }}
        git checkout pr-head

    - name: Build and test
      run: |
        touch build_timing_log.txt
        ./build.sh --diff --regex ${{ matrix.regex }}
        ./processbuildtiminglog.sh
