name: Build push

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build and test
      run: |
        dotnet --info
        touch build_timing_log.txt
        ./build.sh
        ./processbuildtiminglog.sh
