name: Detect differences (PR only)

on: [pull_request]

jobs:

  diff:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 100

    # The GitHub checkout action leaves the repo in a slightly awkward
    # state. This tidies it up.
    - name: Set up git branches
      run: |
        git checkout -b pr-head
        git checkout -b master ${{ github.event.pull_request.base.sha }}
        git checkout pr-head

    - name: Detect PR changes
      run: |
        ./detect-pr-changes.sh
